"""Add CicloAcademico model and link Estudiante

Revision ID: 44657c223167
Revises: 2d3683638033
Create Date: 2026-08-03 16:37:45.913685

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44657c223167'
down_revision = '2d3683638033'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ciclos_academicos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    with op.batch_alter_table('estudiantes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ciclo_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_estudiantes_ciclos', 'ciclos_academicos', ['ciclo_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('estudiantes', schema=None) as batch_op:
        batch_op.drop_constraint('fk_estudiantes_ciclos', type_='foreignkey')
        batch_op.drop_column('ciclo_id')

    op.drop_table('ciclos_academicos')
    # ### end Alembic commands ###
