"""Add drive links and physical document checklist notes

Revision ID: a7198bc8a1e9
Revises: b289c05ed8ad
Create Date: 2026-08-03 15:53:22.835922

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7198bc8a1e9'
down_revision = 'b289c05ed8ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('carreras', schema=None) as batch_op:
        batch_op.add_column(sa.Column('malla_link', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('syllabus_link', sa.String(length=500), nullable=True))

    with op.batch_alter_table('documentos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notes', sa.Text(), nullable=True))
        batch_op.alter_column('file_path',
               existing_type=sa.VARCHAR(length=250),
               nullable=True)
        batch_op.alter_column('filename',
               existing_type=sa.VARCHAR(length=150),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documentos', schema=None) as batch_op:
        batch_op.alter_column('filename',
               existing_type=sa.VARCHAR(length=150),
               nullable=False)
        batch_op.alter_column('file_path',
               existing_type=sa.VARCHAR(length=250),
               nullable=False)
        batch_op.drop_column('notes')

    with op.batch_alter_table('carreras', schema=None) as batch_op:
        batch_op.drop_column('syllabus_link')
        batch_op.drop_column('malla_link')

    # ### end Alembic commands ###
